require("tyler.plugins-setup")
require("tyler.core.options")
require("tyler.core.keymaps")
require("tyler.core.colorscheme")
require("tyler.plugins.comment")
require("tyler.plugins.nvim-tree")
require("tyler.plugins.lualine")
require("tyler.plugins.telescope")
-- require("tyler.plugins.nvim-cmp")
